config/routes.rb
Rails.application.routes.draw do
	
  	# devise_for :authors

  	devise_for :authors, controllers: {  
	  passwords: 'authors/passwords',
	  sessions: 'authors/sessions',
	  confirmations: 'authors/confirmations',
	  registrations: 'authors/registrations',
	}

	as :author do
		get 'login' => 'authors/sessions#new', as: :new_user_session
		# get 'update' => 'authors/registrations#new', as: :edit_author_registration_path
	end

	root to: "blog/posts#index"

	namespace :authors do
		get 'account' => 'accounts#show', as: :account
		# get 'account/edit' => 'accounts#edit', as: :edit_account
		resources :posts
	end

	scope module: 'blog' do
  		get 'about' => 'pages#about', as: :about
		get 'contact' => 'pages#contact', as: :contact
		get 'posts' => 'posts#index', as: :posts
		get 'posts/:id' => 'posts#show', as: :post
  	end

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	belongs_to :author

    acts_as_taggable

  	scope :most_recent, -> { order('created_at desc') }

    scope :published, -> { where(published: true) }

  	def should_generate_new_friendly_id?
  		title_changed?
  	end

  	def published_on
      if published_at.present?
  		  "#{published_at.strftime("Published on %b %d, %Y - %I:%M%p")}"
      else
        ""
      end
  	end

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
	class AccountsController < AuthorController

		def show
			
		end

		def edit
			
		end

	end
end

app/controllers/authors/confirmations_controller.rb
class Authors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/authors/omniauth_callbacks_controller.rb
class Authors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/authors/passwords_controller.rb
class Authors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/authors/posts_controller.rb
module Authors
	class PostsController < AuthorController
	  before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	    @posts = current_author.posts.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  end

	  # GET /posts/new
	  def new
	    @post = current_author.posts.new
	  end

	  # GET /posts/1/edit
	  def edit
	  end

	  # POST /posts
	  # POST /posts.json
	  def create
	    @post = current_author.posts.new(post_params)

	    respond_to do |format|
	      if @post.save
	        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
	        format.json { render :show, status: :created, location: @post }
	      else
	        format.html { render :new }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # PATCH/PUT /posts/1
	  # PATCH/PUT /posts/1.json
	  def update
	  	@post.update(published_at: Time.now)
	    respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to authors_post_url(@post), notice: 'Post was successfully updated.' }
	        format.json { render :show, status: :ok, location: @post }
	      else
	        format.html { render :edit }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /posts/1
	  # DELETE /posts/1.json
	  def destroy
	    @post.destroy
	    respond_to do |format|
	      format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_post
	      @post = current_author.posts.friendly.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def post_params
	      params.require(:post).permit(:title, :body, :description, :banner_image_url, :published, :tag_list)
	    end
	end

end

app/controllers/authors/registrations_controller.rb
class Authors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    redirect_to authors_account_path
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:bio])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:bio])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/authors/sessions_controller.rb
class Authors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/authors/unlocks_controller.rb
class Authors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/blog/posts_controller.rb
module Blog
	class PostsController < BlogController

	  # GET /posts
	  # GET /posts.json
	  def index
	  	if params[:tag]
	    	@posts = Post.most_recent.published.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 5)
	  	else
	  		@posts = Post.most_recent.published.paginate(:page => params[:page], :per_page => 5)
	  	end
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  	@post = Post.published.friendly.find(params[:id])
	  end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-4">


        <div class="card">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="field">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>
              </div>          
            </li>
            <!-- Remember to pust the bublished here -->
            <li class="list-group-item">
              <div class="field">
                <%= f.label :published %>
                <%= f.check_box :published %>
              </div>          
            </li>
            <!-- Here -->
            <li class="list-group-item">
              <div class="field">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
              </div>              
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label :banner_image_url %>
                <%= f.text_area :banner_image_url, class: 'form-control' %>
              </div>              
            </li>
            <li class="list-group-item">
              <div class="field">
                <%= f.label "Tags" %>
                <%= f.text_area :tag_list, class: 'form-control' %>
              </div>              
            </li>
            <li class="list-group-item">
              <div class="actions">
                <%= f.submit 'Save Post', class: 'btn btn-success btn-block' %>
              </div>             
            </li>
          </ul>
        </div>

        <% if post.persisted? %>
          <%= link_to 'Show', @post %> |
        <% end %>
        <%= link_to 'Back', authors_posts_path %>
      </div>

      <div class="col-md-8">  
        <div class="field">
          <%= f.text_area :body %>
        </div>
      </div>

  </div>

<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td> <%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %> </td>
	<td> <%= link_to 'Delete', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %> </td>
	<% if post.published %>
		<td>Published</td>
	<% else %>
		<td>-</td>
	<% end %>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, "active") %>

<h3>Edit <%= @post.title %></h3>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, "All Posts") %>
<% provide(:author, "active") %>

<div class="row">
	<div>
		<%= link_to 'New Post', new_authors_post_path, class: 'btn btn-md btn-primary' %>		
	</div>
	<table class="table table-striped">
		<tr>
			<th>Title</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<%= render @posts %>
	</table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:author, "active") %>
<% provide(:page_title, 'New Post') %>

<h3>New Post</h3>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, "active") %>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.created_at %></p>
		<p><%= @post.body.html_safe %></p>
		<%= link_to 'Edit', edit_authors_post_path(@post) %> |
		<%= link_to 'Delete', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %> |
		<%= link_to 'Back', authors_posts_path %>
	</div>
</div>