config/routes.rb
Rails.application.routes.draw do
	
  	# devise_for :authors

  	devise_for :authors, controllers: {  
	  passwords: 'authors/passwords',
	  sessions: 'authors/sessions',
	  confirmations: 'authors/confirmations',
	  registrations: 'authors/registrations',
	}

	as :author do
		get 'login' => 'authors/sessions#new', as: :new_user_session
		# get 'update' => 'authors/registrations#new', as: :edit_author_registration_path
	end

	root to: "blog/posts#index"

	namespace :authors do
		get 'account' => 'accounts#show', as: :account
		# get 'account/edit' => 'accounts#edit', as: :edit_account
		resources :posts
	end

	scope module: 'blog' do
  		get 'about' => 'pages#about', as: :about
		get 'contact' => 'pages#contact', as: :contact
		get 'posts' => 'posts#index', as: :posts
		get 'posts/:id' => 'posts#show', as: :post
  	end

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
<div class="container">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "FROG Blog", root_path, class: "navbar-brand mb-0" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= yield(:blog_active) %> ">
        <%= link_to 'Blog', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= yield(:about_active) %> ">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= yield(:contact_active) %> ">
        <%= link_to 'contact', contact_path, class: "nav-link" %>
      </li>
      <% if author_signed_in? %>
        <li class="nav-item dropdown <%= yield(:author) %>">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Author
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'My posts', authors_posts_path, class: "dropdown-item" %>
            <%= link_to 'Profile', authors_account_path, class: "dropdown-item" %>
            <%= link_to 'Edit Info', edit_author_registration_path, class: "dropdown-item" %>
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>

  </div>
  
</div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | FrogBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  </head>

  <body>

  <%= render 'layouts/navbar' %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container <%= controller_name %> <%= action_name %>">
  	<%= yield %>
  </div>
    

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %> | FrogBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/navbar' %>
  
  <div class="container <%= controller_name %> <%= action_name %>">
  	<%= yield %>
  </div>
    

  <script id="dsq-count-scr" src="//frogblog-2.disqus.com/count.js" async></script>
  </body>
</html>